// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/types/language.proto (package ablibrary.types, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata, MetadataJson } from "./metadata_pb";
import { file_ablibrary_types_metadata } from "./metadata_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/types/language.proto.
 */
export const file_ablibrary_types_language: GenFile = /*@__PURE__*/
  fileDesc("Ch5hYmxpYnJhcnkvdHlwZXMvbGFuZ3VhZ2UucHJvdG8SD2FibGlicmFyeS50eXBlcyKZAQoITGFuZ3VhZ2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIOCgZ3ZWlnaHQYAyABKAUSNgoOdGV4dF9kaXJlY3Rpb24YBCABKA4yHi5hYmxpYnJhcnkudHlwZXMuVGV4dERpcmVjdGlvbhIrCghtZXRhZGF0YRgFIAEoCzIZLmFibGlicmFyeS50eXBlcy5NZXRhZGF0YSpfCg1UZXh0RGlyZWN0aW9uEh4KGlRFWFRfRElSRUNUSU9OX1VOU1BFQ0lGSUVEEAASFgoSVEVYVF9ESVJFQ1RJT05fTFRSEAESFgoSVEVYVF9ESVJFQ1RJT05fUlRMEAJCMVodYWJsaWJyYXJ5Lm5ldC9hcGkvcHJvdG8vdHlwZXOqAg9BQkxpYnJhcnkuVHlwZXNiCGVkaXRpb25zcOgH", [file_ablibrary_types_metadata]);

/**
 * @generated from message ablibrary.types.Language
 */
export type Language = Message<"ablibrary.types.Language"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 weight = 3;
   */
  weight: number;

  /**
   * @generated from field: ablibrary.types.TextDirection text_direction = 4;
   */
  textDirection: TextDirection;

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 5;
   */
  metadata?: Metadata;
};

/**
 * @generated from message ablibrary.types.Language
 */
export type LanguageJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * @generated from field: int32 weight = 3;
   */
  weight?: number;

  /**
   * @generated from field: ablibrary.types.TextDirection text_direction = 4;
   */
  textDirection?: TextDirectionJson;

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 5;
   */
  metadata?: MetadataJson;
};

/**
 * Describes the message ablibrary.types.Language.
 * Use `create(LanguageSchema)` to create a new message.
 */
export const LanguageSchema: GenMessage<Language, {jsonType: LanguageJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_types_language, 0);

/**
 * @generated from enum ablibrary.types.TextDirection
 */
export enum TextDirection {
  /**
   * @generated from enum value: TEXT_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TEXT_DIRECTION_LTR = 1;
   */
  LTR = 1,

  /**
   * @generated from enum value: TEXT_DIRECTION_RTL = 2;
   */
  RTL = 2,
}

/**
 * @generated from enum ablibrary.types.TextDirection
 */
export type TextDirectionJson = "TEXT_DIRECTION_UNSPECIFIED" | "TEXT_DIRECTION_LTR" | "TEXT_DIRECTION_RTL";

/**
 * Describes the enum ablibrary.types.TextDirection.
 */
export const TextDirectionSchema: GenEnum<TextDirection, TextDirectionJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_types_language, 0);

