// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/schema/role_permission_schema.proto (package ablibrary.schema, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "../types/common_pb";
import { file_ablibrary_types_common } from "../types/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/schema/role_permission_schema.proto.
 */
export const file_ablibrary_schema_role_permission_schema: GenFile = /*@__PURE__*/
  fileDesc("Ci1hYmxpYnJhcnkvc2NoZW1hL3JvbGVfcGVybWlzc2lvbl9zY2hlbWEucHJvdG8SEGFibGlicmFyeS5zY2hlbWEiZgoUUm9sZVBlcm1pc3Npb25TY2hlbWESDwoHcm9sZV9pZBgBIAEoCRIVCg1wZXJtaXNzaW9uX2lkGAIgASgJEhIKCmNyZWF0ZWRfYXQYAyABKAMSEgoKdXBkYXRlZF9hdBgEIAEoAyLhBAobUm9sZVBlcm1pc3Npb25TY2hlbWFGaWx0ZXJzEkUKB3JvbGVfaWQYASADKAsyNC5hYmxpYnJhcnkuc2NoZW1hLlJvbGVQZXJtaXNzaW9uU2NoZW1hRmlsdGVycy5Sb2xlSWQSUQoNcGVybWlzc2lvbl9pZBgCIAMoCzI6LmFibGlicmFyeS5zY2hlbWEuUm9sZVBlcm1pc3Npb25TY2hlbWFGaWx0ZXJzLlBlcm1pc3Npb25JZBJLCgpjcmVhdGVkX2F0GAMgAygLMjcuYWJsaWJyYXJ5LnNjaGVtYS5Sb2xlUGVybWlzc2lvblNjaGVtYUZpbHRlcnMuQ3JlYXRlZEF0EksKCnVwZGF0ZWRfYXQYBCADKAsyNy5hYmxpYnJhcnkuc2NoZW1hLlJvbGVQZXJtaXNzaW9uU2NoZW1hRmlsdGVycy5VcGRhdGVkQXQaJAoGUm9sZUlkEgoKAmVxGAEgAygJEg4KBm5vdF9lcRgCIAMoCRoqCgxQZXJtaXNzaW9uSWQSCgoCZXEYASADKAkSDgoGbm90X2VxGAIgAygJGl0KCUNyZWF0ZWRBdBIoCgRmcm9tGAEgASgLMhouYWJsaWJyYXJ5LnR5cGVzLlRpbWVzdGFtcBImCgJ0bxgCIAEoCzIaLmFibGlicmFyeS50eXBlcy5UaW1lc3RhbXAaXQoJVXBkYXRlZEF0EigKBGZyb20YASABKAsyGi5hYmxpYnJhcnkudHlwZXMuVGltZXN0YW1wEiYKAnRvGAIgASgLMhouYWJsaWJyYXJ5LnR5cGVzLlRpbWVzdGFtcCJAChZSb2xlUGVybWlzc2lvblNjaGVtYUlEEg8KB3JvbGVfaWQYASABKAkSFQoNcGVybWlzc2lvbl9pZBgCIAEoCSrPAQoZUm9sZVBlcm1pc3Npb25TY2hlbWFGaWVsZBIoCiRST0xFX1BFUk1JU1NJT05fU0NIRU1BX0ZJRUxEX1JPTEVfSUQQABIuCipST0xFX1BFUk1JU1NJT05fU0NIRU1BX0ZJRUxEX1BFUk1JU1NJT05fSUQQARIrCidST0xFX1BFUk1JU1NJT05fU0NIRU1BX0ZJRUxEX0NSRUFURURfQVQQAhIrCidST0xFX1BFUk1JU1NJT05fU0NIRU1BX0ZJRUxEX1VQREFURURfQVQQA0IzWh5hYmxpYnJhcnkubmV0L2FwaS9wcm90by9zY2hlbWGqAhBBQkxpYnJhcnkuU2NoZW1hYghlZGl0aW9uc3DoBw", [file_ablibrary_types_common]);

/**
 * @generated from message ablibrary.schema.RolePermissionSchema
 */
export type RolePermissionSchema = Message<"ablibrary.schema.RolePermissionSchema"> & {
  /**
   * @generated from field: string role_id = 1;
   */
  roleId: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 updated_at = 4;
   */
  updatedAt: bigint;
};

/**
 * @generated from message ablibrary.schema.RolePermissionSchema
 */
export type RolePermissionSchemaJson = {
  /**
   * @generated from field: string role_id = 1;
   */
  roleId?: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId?: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt?: string;

  /**
   * @generated from field: int64 updated_at = 4;
   */
  updatedAt?: string;
};

/**
 * Describes the message ablibrary.schema.RolePermissionSchema.
 * Use `create(RolePermissionSchemaSchema)` to create a new message.
 */
export const RolePermissionSchemaSchema: GenMessage<RolePermissionSchema, {jsonType: RolePermissionSchemaJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_role_permission_schema, 0);

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters
 */
export type RolePermissionSchemaFilters = Message<"ablibrary.schema.RolePermissionSchemaFilters"> & {
  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.RoleId role_id = 1;
   */
  roleId: RolePermissionSchemaFilters_RoleId[];

  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.PermissionId permission_id = 2;
   */
  permissionId: RolePermissionSchemaFilters_PermissionId[];

  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.CreatedAt created_at = 3;
   */
  createdAt: RolePermissionSchemaFilters_CreatedAt[];

  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.UpdatedAt updated_at = 4;
   */
  updatedAt: RolePermissionSchemaFilters_UpdatedAt[];
};

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters
 */
export type RolePermissionSchemaFiltersJson = {
  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.RoleId role_id = 1;
   */
  roleId?: RolePermissionSchemaFilters_RoleIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.PermissionId permission_id = 2;
   */
  permissionId?: RolePermissionSchemaFilters_PermissionIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.CreatedAt created_at = 3;
   */
  createdAt?: RolePermissionSchemaFilters_CreatedAtJson[];

  /**
   * @generated from field: repeated ablibrary.schema.RolePermissionSchemaFilters.UpdatedAt updated_at = 4;
   */
  updatedAt?: RolePermissionSchemaFilters_UpdatedAtJson[];
};

/**
 * Describes the message ablibrary.schema.RolePermissionSchemaFilters.
 * Use `create(RolePermissionSchemaFiltersSchema)` to create a new message.
 */
export const RolePermissionSchemaFiltersSchema: GenMessage<RolePermissionSchemaFilters, {jsonType: RolePermissionSchemaFiltersJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_role_permission_schema, 1);

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.RoleId
 */
export type RolePermissionSchemaFilters_RoleId = Message<"ablibrary.schema.RolePermissionSchemaFilters.RoleId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.RoleId
 */
export type RolePermissionSchemaFilters_RoleIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.RolePermissionSchemaFilters.RoleId.
 * Use `create(RolePermissionSchemaFilters_RoleIdSchema)` to create a new message.
 */
export const RolePermissionSchemaFilters_RoleIdSchema: GenMessage<RolePermissionSchemaFilters_RoleId, {jsonType: RolePermissionSchemaFilters_RoleIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_role_permission_schema, 1, 0);

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.PermissionId
 */
export type RolePermissionSchemaFilters_PermissionId = Message<"ablibrary.schema.RolePermissionSchemaFilters.PermissionId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.PermissionId
 */
export type RolePermissionSchemaFilters_PermissionIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.RolePermissionSchemaFilters.PermissionId.
 * Use `create(RolePermissionSchemaFilters_PermissionIdSchema)` to create a new message.
 */
export const RolePermissionSchemaFilters_PermissionIdSchema: GenMessage<RolePermissionSchemaFilters_PermissionId, {jsonType: RolePermissionSchemaFilters_PermissionIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_role_permission_schema, 1, 1);

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.CreatedAt
 */
export type RolePermissionSchemaFilters_CreatedAt = Message<"ablibrary.schema.RolePermissionSchemaFilters.CreatedAt"> & {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: Timestamp;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: Timestamp;
};

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.CreatedAt
 */
export type RolePermissionSchemaFilters_CreatedAtJson = {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: TimestampJson;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: TimestampJson;
};

/**
 * Describes the message ablibrary.schema.RolePermissionSchemaFilters.CreatedAt.
 * Use `create(RolePermissionSchemaFilters_CreatedAtSchema)` to create a new message.
 */
export const RolePermissionSchemaFilters_CreatedAtSchema: GenMessage<RolePermissionSchemaFilters_CreatedAt, {jsonType: RolePermissionSchemaFilters_CreatedAtJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_role_permission_schema, 1, 2);

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.UpdatedAt
 */
export type RolePermissionSchemaFilters_UpdatedAt = Message<"ablibrary.schema.RolePermissionSchemaFilters.UpdatedAt"> & {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: Timestamp;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: Timestamp;
};

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaFilters.UpdatedAt
 */
export type RolePermissionSchemaFilters_UpdatedAtJson = {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: TimestampJson;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: TimestampJson;
};

/**
 * Describes the message ablibrary.schema.RolePermissionSchemaFilters.UpdatedAt.
 * Use `create(RolePermissionSchemaFilters_UpdatedAtSchema)` to create a new message.
 */
export const RolePermissionSchemaFilters_UpdatedAtSchema: GenMessage<RolePermissionSchemaFilters_UpdatedAt, {jsonType: RolePermissionSchemaFilters_UpdatedAtJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_role_permission_schema, 1, 3);

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaID
 */
export type RolePermissionSchemaID = Message<"ablibrary.schema.RolePermissionSchemaID"> & {
  /**
   * @generated from field: string role_id = 1;
   */
  roleId: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId: string;
};

/**
 * @generated from message ablibrary.schema.RolePermissionSchemaID
 */
export type RolePermissionSchemaIDJson = {
  /**
   * @generated from field: string role_id = 1;
   */
  roleId?: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId?: string;
};

/**
 * Describes the message ablibrary.schema.RolePermissionSchemaID.
 * Use `create(RolePermissionSchemaIDSchema)` to create a new message.
 */
export const RolePermissionSchemaIDSchema: GenMessage<RolePermissionSchemaID, {jsonType: RolePermissionSchemaIDJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_role_permission_schema, 2);

/**
 * @generated from enum ablibrary.schema.RolePermissionSchemaField
 */
export enum RolePermissionSchemaField {
  /**
   * @generated from enum value: ROLE_PERMISSION_SCHEMA_FIELD_ROLE_ID = 0;
   */
  ROLE_ID = 0,

  /**
   * @generated from enum value: ROLE_PERMISSION_SCHEMA_FIELD_PERMISSION_ID = 1;
   */
  PERMISSION_ID = 1,

  /**
   * @generated from enum value: ROLE_PERMISSION_SCHEMA_FIELD_CREATED_AT = 2;
   */
  CREATED_AT = 2,

  /**
   * @generated from enum value: ROLE_PERMISSION_SCHEMA_FIELD_UPDATED_AT = 3;
   */
  UPDATED_AT = 3,
}

/**
 * @generated from enum ablibrary.schema.RolePermissionSchemaField
 */
export type RolePermissionSchemaFieldJson = "ROLE_PERMISSION_SCHEMA_FIELD_ROLE_ID" | "ROLE_PERMISSION_SCHEMA_FIELD_PERMISSION_ID" | "ROLE_PERMISSION_SCHEMA_FIELD_CREATED_AT" | "ROLE_PERMISSION_SCHEMA_FIELD_UPDATED_AT";

/**
 * Describes the enum ablibrary.schema.RolePermissionSchemaField.
 */
export const RolePermissionSchemaFieldSchema: GenEnum<RolePermissionSchemaField, RolePermissionSchemaFieldJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_schema_role_permission_schema, 0);

