// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/schema/tag_schema.proto (package ablibrary.schema, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "../types/common_pb";
import { file_ablibrary_types_common } from "../types/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/schema/tag_schema.proto.
 */
export const file_ablibrary_schema_tag_schema: GenFile = /*@__PURE__*/
  fileDesc("CiFhYmxpYnJhcnkvc2NoZW1hL3RhZ19zY2hlbWEucHJvdG8SEGFibGlicmFyeS5zY2hlbWEiUwoJVGFnU2NoZW1hEgoKAmlkGAEgASgJEhIKCmNyZWF0ZWRfYXQYAiABKAMSEgoKdXBkYXRlZF9hdBgDIAEoAxISCgpkZWxldGVkX2F0GAQgASgDIu4EChBUYWdTY2hlbWFGaWx0ZXJzEjEKAmlkGAEgAygLMiUuYWJsaWJyYXJ5LnNjaGVtYS5UYWdTY2hlbWFGaWx0ZXJzLklkEkAKCmNyZWF0ZWRfYXQYAiADKAsyLC5hYmxpYnJhcnkuc2NoZW1hLlRhZ1NjaGVtYUZpbHRlcnMuQ3JlYXRlZEF0EkAKCnVwZGF0ZWRfYXQYAyADKAsyLC5hYmxpYnJhcnkuc2NoZW1hLlRhZ1NjaGVtYUZpbHRlcnMuVXBkYXRlZEF0EkAKCmRlbGV0ZWRfYXQYBCADKAsyLC5hYmxpYnJhcnkuc2NoZW1hLlRhZ1NjaGVtYUZpbHRlcnMuRGVsZXRlZEF0GiAKAklkEgoKAmVxGAEgAygJEg4KBm5vdF9lcRgCIAMoCRpdCglDcmVhdGVkQXQSKAoEZnJvbRgBIAEoCzIaLmFibGlicmFyeS50eXBlcy5UaW1lc3RhbXASJgoCdG8YAiABKAsyGi5hYmxpYnJhcnkudHlwZXMuVGltZXN0YW1wGl0KCVVwZGF0ZWRBdBIoCgRmcm9tGAEgASgLMhouYWJsaWJyYXJ5LnR5cGVzLlRpbWVzdGFtcBImCgJ0bxgCIAEoCzIaLmFibGlicmFyeS50eXBlcy5UaW1lc3RhbXAagAEKCURlbGV0ZWRBdBIPCgdpc19udWxsGAEgASgIEhAKCG5vdF9udWxsGAIgASgIEigKBGZyb20YAyABKAsyGi5hYmxpYnJhcnkudHlwZXMuVGltZXN0YW1wEiYKAnRvGAQgASgLMhouYWJsaWJyYXJ5LnR5cGVzLlRpbWVzdGFtcCqMAQoOVGFnU2NoZW1hRmllbGQSFwoTVEFHX1NDSEVNQV9GSUVMRF9JRBAAEh8KG1RBR19TQ0hFTUFfRklFTERfQ1JFQVRFRF9BVBABEh8KG1RBR19TQ0hFTUFfRklFTERfVVBEQVRFRF9BVBACEh8KG1RBR19TQ0hFTUFfRklFTERfREVMRVRFRF9BVBADQjNaHmFibGlicmFyeS5uZXQvYXBpL3Byb3RvL3NjaGVtYaoCEEFCTGlicmFyeS5TY2hlbWFiCGVkaXRpb25zcOgH", [file_ablibrary_types_common]);

/**
 * @generated from message ablibrary.schema.TagSchema
 */
export type TagSchema = Message<"ablibrary.schema.TagSchema"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 created_at = 2;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 updated_at = 3;
   */
  updatedAt: bigint;

  /**
   * @generated from field: int64 deleted_at = 4;
   */
  deletedAt: bigint;
};

/**
 * @generated from message ablibrary.schema.TagSchema
 */
export type TagSchemaJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: int64 created_at = 2;
   */
  createdAt?: string;

  /**
   * @generated from field: int64 updated_at = 3;
   */
  updatedAt?: string;

  /**
   * @generated from field: int64 deleted_at = 4;
   */
  deletedAt?: string;
};

/**
 * Describes the message ablibrary.schema.TagSchema.
 * Use `create(TagSchemaSchema)` to create a new message.
 */
export const TagSchemaSchema: GenMessage<TagSchema, {jsonType: TagSchemaJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_schema, 0);

/**
 * @generated from message ablibrary.schema.TagSchemaFilters
 */
export type TagSchemaFilters = Message<"ablibrary.schema.TagSchemaFilters"> & {
  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.Id id = 1;
   */
  id: TagSchemaFilters_Id[];

  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.CreatedAt created_at = 2;
   */
  createdAt: TagSchemaFilters_CreatedAt[];

  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.UpdatedAt updated_at = 3;
   */
  updatedAt: TagSchemaFilters_UpdatedAt[];

  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.DeletedAt deleted_at = 4;
   */
  deletedAt: TagSchemaFilters_DeletedAt[];
};

/**
 * @generated from message ablibrary.schema.TagSchemaFilters
 */
export type TagSchemaFiltersJson = {
  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.Id id = 1;
   */
  id?: TagSchemaFilters_IdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.CreatedAt created_at = 2;
   */
  createdAt?: TagSchemaFilters_CreatedAtJson[];

  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.UpdatedAt updated_at = 3;
   */
  updatedAt?: TagSchemaFilters_UpdatedAtJson[];

  /**
   * @generated from field: repeated ablibrary.schema.TagSchemaFilters.DeletedAt deleted_at = 4;
   */
  deletedAt?: TagSchemaFilters_DeletedAtJson[];
};

/**
 * Describes the message ablibrary.schema.TagSchemaFilters.
 * Use `create(TagSchemaFiltersSchema)` to create a new message.
 */
export const TagSchemaFiltersSchema: GenMessage<TagSchemaFilters, {jsonType: TagSchemaFiltersJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_schema, 1);

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.Id
 */
export type TagSchemaFilters_Id = Message<"ablibrary.schema.TagSchemaFilters.Id"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.Id
 */
export type TagSchemaFilters_IdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.TagSchemaFilters.Id.
 * Use `create(TagSchemaFilters_IdSchema)` to create a new message.
 */
export const TagSchemaFilters_IdSchema: GenMessage<TagSchemaFilters_Id, {jsonType: TagSchemaFilters_IdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_schema, 1, 0);

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.CreatedAt
 */
export type TagSchemaFilters_CreatedAt = Message<"ablibrary.schema.TagSchemaFilters.CreatedAt"> & {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: Timestamp;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: Timestamp;
};

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.CreatedAt
 */
export type TagSchemaFilters_CreatedAtJson = {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: TimestampJson;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: TimestampJson;
};

/**
 * Describes the message ablibrary.schema.TagSchemaFilters.CreatedAt.
 * Use `create(TagSchemaFilters_CreatedAtSchema)` to create a new message.
 */
export const TagSchemaFilters_CreatedAtSchema: GenMessage<TagSchemaFilters_CreatedAt, {jsonType: TagSchemaFilters_CreatedAtJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_schema, 1, 1);

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.UpdatedAt
 */
export type TagSchemaFilters_UpdatedAt = Message<"ablibrary.schema.TagSchemaFilters.UpdatedAt"> & {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: Timestamp;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: Timestamp;
};

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.UpdatedAt
 */
export type TagSchemaFilters_UpdatedAtJson = {
  /**
   * @generated from field: ablibrary.types.Timestamp from = 1;
   */
  from?: TimestampJson;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 2;
   */
  to?: TimestampJson;
};

/**
 * Describes the message ablibrary.schema.TagSchemaFilters.UpdatedAt.
 * Use `create(TagSchemaFilters_UpdatedAtSchema)` to create a new message.
 */
export const TagSchemaFilters_UpdatedAtSchema: GenMessage<TagSchemaFilters_UpdatedAt, {jsonType: TagSchemaFilters_UpdatedAtJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_schema, 1, 2);

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.DeletedAt
 */
export type TagSchemaFilters_DeletedAt = Message<"ablibrary.schema.TagSchemaFilters.DeletedAt"> & {
  /**
   * @generated from field: bool is_null = 1;
   */
  isNull: boolean;

  /**
   * @generated from field: bool not_null = 2;
   */
  notNull: boolean;

  /**
   * @generated from field: ablibrary.types.Timestamp from = 3;
   */
  from?: Timestamp;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 4;
   */
  to?: Timestamp;
};

/**
 * @generated from message ablibrary.schema.TagSchemaFilters.DeletedAt
 */
export type TagSchemaFilters_DeletedAtJson = {
  /**
   * @generated from field: bool is_null = 1;
   */
  isNull?: boolean;

  /**
   * @generated from field: bool not_null = 2;
   */
  notNull?: boolean;

  /**
   * @generated from field: ablibrary.types.Timestamp from = 3;
   */
  from?: TimestampJson;

  /**
   * @generated from field: ablibrary.types.Timestamp to = 4;
   */
  to?: TimestampJson;
};

/**
 * Describes the message ablibrary.schema.TagSchemaFilters.DeletedAt.
 * Use `create(TagSchemaFilters_DeletedAtSchema)` to create a new message.
 */
export const TagSchemaFilters_DeletedAtSchema: GenMessage<TagSchemaFilters_DeletedAt, {jsonType: TagSchemaFilters_DeletedAtJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_schema, 1, 3);

/**
 * @generated from enum ablibrary.schema.TagSchemaField
 */
export enum TagSchemaField {
  /**
   * @generated from enum value: TAG_SCHEMA_FIELD_ID = 0;
   */
  ID = 0,

  /**
   * @generated from enum value: TAG_SCHEMA_FIELD_CREATED_AT = 1;
   */
  CREATED_AT = 1,

  /**
   * @generated from enum value: TAG_SCHEMA_FIELD_UPDATED_AT = 2;
   */
  UPDATED_AT = 2,

  /**
   * @generated from enum value: TAG_SCHEMA_FIELD_DELETED_AT = 3;
   */
  DELETED_AT = 3,
}

/**
 * @generated from enum ablibrary.schema.TagSchemaField
 */
export type TagSchemaFieldJson = "TAG_SCHEMA_FIELD_ID" | "TAG_SCHEMA_FIELD_CREATED_AT" | "TAG_SCHEMA_FIELD_UPDATED_AT" | "TAG_SCHEMA_FIELD_DELETED_AT";

/**
 * Describes the enum ablibrary.schema.TagSchemaField.
 */
export const TagSchemaFieldSchema: GenEnum<TagSchemaField, TagSchemaFieldJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_schema_tag_schema, 0);

