// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/types/field_mask.proto (package ablibrary.types, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldMask as FieldMask$1, FieldMaskJson as FieldMaskJson$1 } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/types/field_mask.proto.
 */
export const file_ablibrary_types_field_mask: GenFile = /*@__PURE__*/
  fileDesc("CiBhYmxpYnJhcnkvdHlwZXMvZmllbGRfbWFzay5wcm90bxIPYWJsaWJyYXJ5LnR5cGVzIqoBCglGaWVsZE1hc2sSKAoEb25seRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2sSKgoGZXhjZXB0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzaxI0Cgh0ZW1wbGF0ZRgDIAEoDjIiLmFibGlicmFyeS50eXBlcy5GaWVsZE1hc2tUZW1wbGF0ZRIRCgltYXhfZGVwdGgYBCABKAUqjgEKEUZpZWxkTWFza1RlbXBsYXRlEhwKGEZJRUxEX01BU0tfVEVNUExBVEVfRlVMTBAAEh0KGUZJRUxEX01BU0tfVEVNUExBVEVfQkFTSUMQARIaChZGSUVMRF9NQVNLX1RFTVBMQVRFX0lEEAISIAocRklFTERfTUFTS19URU1QTEFURV9JRF9MQUJFTBADQjFaHWFibGlicmFyeS5uZXQvYXBpL3Byb3RvL3R5cGVzqgIPQUJMaWJyYXJ5LlR5cGVzYghlZGl0aW9uc3DoBw", [file_google_protobuf_field_mask]);

/**
 * @generated from message ablibrary.types.FieldMask
 */
export type FieldMask = Message<"ablibrary.types.FieldMask"> & {
  /**
   * @generated from field: google.protobuf.FieldMask only = 1;
   */
  only?: FieldMask$1;

  /**
   * @generated from field: google.protobuf.FieldMask except = 2;
   */
  except?: FieldMask$1;

  /**
   * @generated from field: ablibrary.types.FieldMaskTemplate template = 3;
   */
  template: FieldMaskTemplate;

  /**
   * @generated from field: int32 max_depth = 4;
   */
  maxDepth: number;
};

/**
 * @generated from message ablibrary.types.FieldMask
 */
export type FieldMaskJson = {
  /**
   * @generated from field: google.protobuf.FieldMask only = 1;
   */
  only?: FieldMaskJson$1;

  /**
   * @generated from field: google.protobuf.FieldMask except = 2;
   */
  except?: FieldMaskJson$1;

  /**
   * @generated from field: ablibrary.types.FieldMaskTemplate template = 3;
   */
  template?: FieldMaskTemplateJson;

  /**
   * @generated from field: int32 max_depth = 4;
   */
  maxDepth?: number;
};

/**
 * Describes the message ablibrary.types.FieldMask.
 * Use `create(FieldMaskSchema)` to create a new message.
 */
export const FieldMaskSchema: GenMessage<FieldMask, {jsonType: FieldMaskJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_types_field_mask, 0);

/**
 * @generated from enum ablibrary.types.FieldMaskTemplate
 */
export enum FieldMaskTemplate {
  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_FULL = 0;
   */
  FULL = 0,

  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_BASIC = 1;
   */
  BASIC = 1,

  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_ID = 2;
   */
  ID = 2,

  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_ID_LABEL = 3;
   */
  ID_LABEL = 3,
}

/**
 * @generated from enum ablibrary.types.FieldMaskTemplate
 */
export type FieldMaskTemplateJson = "FIELD_MASK_TEMPLATE_FULL" | "FIELD_MASK_TEMPLATE_BASIC" | "FIELD_MASK_TEMPLATE_ID" | "FIELD_MASK_TEMPLATE_ID_LABEL";

/**
 * Describes the enum ablibrary.types.FieldMaskTemplate.
 */
export const FieldMaskTemplateSchema: GenEnum<FieldMaskTemplate, FieldMaskTemplateJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_types_field_mask, 0);

