// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/types/contribution.proto (package ablibrary.types, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata, MetadataJson } from "./metadata_pb";
import { file_ablibrary_types_metadata } from "./metadata_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/types/contribution.proto.
 */
export const file_ablibrary_types_contribution: GenFile = /*@__PURE__*/
  fileDesc("CiJhYmxpYnJhcnkvdHlwZXMvY29udHJpYnV0aW9uLnByb3RvEg9hYmxpYnJhcnkudHlwZXMiiQEKDENvbnRyaWJ1dGlvbhIKCgJpZBgBIAEoCRIMCgRzbHVnGAIgASgJEg0KBXRpdGxlGAMgASgJEg4KBndlaWdodBgEIAEoBRITCgtkZXNjcmlwdGlvbhgFIAEoCRIrCghtZXRhZGF0YRgGIAEoCzIZLmFibGlicmFyeS50eXBlcy5NZXRhZGF0YUIxWh1hYmxpYnJhcnkubmV0L2FwaS9wcm90by90eXBlc6oCD0FCTGlicmFyeS5UeXBlc2IIZWRpdGlvbnNw6Ac", [file_ablibrary_types_metadata]);

/**
 * @generated from message ablibrary.types.Contribution
 */
export type Contribution = Message<"ablibrary.types.Contribution"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string slug = 2;
   */
  slug: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: int32 weight = 4;
   */
  weight: number;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 6;
   */
  metadata?: Metadata;
};

/**
 * @generated from message ablibrary.types.Contribution
 */
export type ContributionJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string slug = 2;
   */
  slug?: string;

  /**
   * @generated from field: string title = 3;
   */
  title?: string;

  /**
   * @generated from field: int32 weight = 4;
   */
  weight?: number;

  /**
   * @generated from field: string description = 5;
   */
  description?: string;

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 6;
   */
  metadata?: MetadataJson;
};

/**
 * Describes the message ablibrary.types.Contribution.
 * Use `create(ContributionSchema)` to create a new message.
 */
export const ContributionSchema: GenMessage<Contribution, {jsonType: ContributionJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_types_contribution, 0);

