// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/types/country.proto (package ablibrary.types, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata, MetadataJson } from "./metadata_pb";
import { file_ablibrary_types_metadata } from "./metadata_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/types/country.proto.
 */
export const file_ablibrary_types_country: GenFile = /*@__PURE__*/
  fileDesc("Ch1hYmxpYnJhcnkvdHlwZXMvY291bnRyeS5wcm90bxIPYWJsaWJyYXJ5LnR5cGVzIlAKB0NvdW50cnkSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIrCghtZXRhZGF0YRgDIAEoCzIZLmFibGlicmFyeS50eXBlcy5NZXRhZGF0YUIxWh1hYmxpYnJhcnkubmV0L2FwaS9wcm90by90eXBlc6oCD0FCTGlicmFyeS5UeXBlc2IIZWRpdGlvbnNw6Ac", [file_ablibrary_types_metadata]);

/**
 * @generated from message ablibrary.types.Country
 */
export type Country = Message<"ablibrary.types.Country"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 3;
   */
  metadata?: Metadata;
};

/**
 * @generated from message ablibrary.types.Country
 */
export type CountryJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 3;
   */
  metadata?: MetadataJson;
};

/**
 * Describes the message ablibrary.types.Country.
 * Use `create(CountrySchema)` to create a new message.
 */
export const CountrySchema: GenMessage<Country, {jsonType: CountryJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_types_country, 0);

