// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/types/metadata.proto (package ablibrary.types, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DateTime, DateTimeJson } from "./common_pb";
import { file_ablibrary_types_common } from "./common_pb";
import type { User, UserJson } from "./user_pb";
import { file_ablibrary_types_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/types/metadata.proto.
 */
export const file_ablibrary_types_metadata: GenFile = /*@__PURE__*/
  fileDesc("Ch5hYmxpYnJhcnkvdHlwZXMvbWV0YWRhdGEucHJvdG8SD2FibGlicmFyeS50eXBlcyLlAQoITWV0YWRhdGESLQoKY3JlYXRlZF9hdBgBIAEoCzIZLmFibGlicmFyeS50eXBlcy5EYXRlVGltZRItCgp1cGRhdGVkX2F0GAIgASgLMhkuYWJsaWJyYXJ5LnR5cGVzLkRhdGVUaW1lEi0KCmRlbGV0ZWRfYXQYAyABKAsyGS5hYmxpYnJhcnkudHlwZXMuRGF0ZVRpbWUSIwoEdXNlchgEIAEoCzIVLmFibGlicmFyeS50eXBlcy5Vc2VyEicKBnN0YXR1cxgFIAEoDjIXLmFibGlicmFyeS50eXBlcy5TdGF0dXMq0gEKBlN0YXR1cxIWChJTVEFUVVNfVU5TUEVDSUZJRUQQABIQCgxTVEFUVVNfRFJBRlQQARIXChNTVEFUVVNfVU5ERVJfUkVWSUVXEAISGwoXU1RBVFVTX05FRURTX0NPUlJFQ1RJT04QAxIUChBTVEFUVVNfUFVCTElTSEVEEAQSEwoPU1RBVFVTX1ZFUklGSUVEEAUSFgoSU1RBVFVTX1VOUFVCTElTSEVEEAYSEwoPU1RBVFVTX1JFSkVDVEVEEAcSEAoMU1RBVFVTX0xPQ0FMEAhCMVodYWJsaWJyYXJ5Lm5ldC9hcGkvcHJvdG8vdHlwZXOqAg9BQkxpYnJhcnkuVHlwZXNiCGVkaXRpb25zcOgH", [file_ablibrary_types_common, file_ablibrary_types_user]);

/**
 * @generated from message ablibrary.types.Metadata
 */
export type Metadata = Message<"ablibrary.types.Metadata"> & {
  /**
   * @generated from field: ablibrary.types.DateTime created_at = 1;
   */
  createdAt?: DateTime;

  /**
   * @generated from field: ablibrary.types.DateTime updated_at = 2;
   */
  updatedAt?: DateTime;

  /**
   * @generated from field: ablibrary.types.DateTime deleted_at = 3;
   */
  deletedAt?: DateTime;

  /**
   * @generated from field: ablibrary.types.User user = 4;
   */
  user?: User;

  /**
   * @generated from field: ablibrary.types.Status status = 5;
   */
  status: Status;
};

/**
 * @generated from message ablibrary.types.Metadata
 */
export type MetadataJson = {
  /**
   * @generated from field: ablibrary.types.DateTime created_at = 1;
   */
  createdAt?: DateTimeJson;

  /**
   * @generated from field: ablibrary.types.DateTime updated_at = 2;
   */
  updatedAt?: DateTimeJson;

  /**
   * @generated from field: ablibrary.types.DateTime deleted_at = 3;
   */
  deletedAt?: DateTimeJson;

  /**
   * @generated from field: ablibrary.types.User user = 4;
   */
  user?: UserJson;

  /**
   * @generated from field: ablibrary.types.Status status = 5;
   */
  status?: StatusJson;
};

/**
 * Describes the message ablibrary.types.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata, {jsonType: MetadataJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_types_metadata, 0);

/**
 * @generated from enum ablibrary.types.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: STATUS_UNDER_REVIEW = 2;
   */
  UNDER_REVIEW = 2,

  /**
   * @generated from enum value: STATUS_NEEDS_CORRECTION = 3;
   */
  NEEDS_CORRECTION = 3,

  /**
   * @generated from enum value: STATUS_PUBLISHED = 4;
   */
  PUBLISHED = 4,

  /**
   * @generated from enum value: STATUS_VERIFIED = 5;
   */
  VERIFIED = 5,

  /**
   * @generated from enum value: STATUS_UNPUBLISHED = 6;
   */
  UNPUBLISHED = 6,

  /**
   * @generated from enum value: STATUS_REJECTED = 7;
   */
  REJECTED = 7,

  /**
   * @generated from enum value: STATUS_LOCAL = 8;
   */
  LOCAL = 8,
}

/**
 * @generated from enum ablibrary.types.Status
 */
export type StatusJson = "STATUS_UNSPECIFIED" | "STATUS_DRAFT" | "STATUS_UNDER_REVIEW" | "STATUS_NEEDS_CORRECTION" | "STATUS_PUBLISHED" | "STATUS_VERIFIED" | "STATUS_UNPUBLISHED" | "STATUS_REJECTED" | "STATUS_LOCAL";

/**
 * Describes the enum ablibrary.types.Status.
 */
export const StatusSchema: GenEnum<Status, StatusJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_types_metadata, 0);

