// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/types/page.proto (package ablibrary.types, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata, MetadataJson } from "./metadata_pb";
import { file_ablibrary_types_metadata } from "./metadata_pb";
import type { PageContent, PageContentJson } from "./page_content_pb";
import { file_ablibrary_types_page_content } from "./page_content_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/types/page.proto.
 */
export const file_ablibrary_types_page: GenFile = /*@__PURE__*/
  fileDesc("ChphYmxpYnJhcnkvdHlwZXMvcGFnZS5wcm90bxIPYWJsaWJyYXJ5LnR5cGVzIusBCgRQYWdlEgoKAmlkGAEgASgJEg8KB2Jvb2tfaWQYAiABKAkSDgoGbnVtYmVyGAMgASgFEg0KBWxhYmVsGAQgASgJEhUKDXNvdXJjZV9udW1iZXIYBSABKAUSFAoMc291cmNlX2xhYmVsGAYgASgJEi4KCGNvbnRlbnRzGAcgAygLMhwuYWJsaWJyYXJ5LnR5cGVzLlBhZ2VDb250ZW50EisKCG1ldGFkYXRhGAggASgLMhkuYWJsaWJyYXJ5LnR5cGVzLk1ldGFkYXRhEh0KFWF0dGFjaG1lbnRfcGFnZV9sYWJlbBgJIAEoCUIxWh1hYmxpYnJhcnkubmV0L2FwaS9wcm90by90eXBlc6oCD0FCTGlicmFyeS5UeXBlc2IIZWRpdGlvbnNw6Ac", [file_ablibrary_types_metadata, file_ablibrary_types_page_content]);

/**
 * @generated from message ablibrary.types.Page
 */
export type Page = Message<"ablibrary.types.Page"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string book_id = 2;
   */
  bookId: string;

  /**
   * @generated from field: int32 number = 3;
   */
  number: number;

  /**
   * @generated from field: string label = 4;
   */
  label: string;

  /**
   * @generated from field: int32 source_number = 5;
   */
  sourceNumber: number;

  /**
   * @generated from field: string source_label = 6;
   */
  sourceLabel: string;

  /**
   * @generated from field: repeated ablibrary.types.PageContent contents = 7;
   */
  contents: PageContent[];

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 8;
   */
  metadata?: Metadata;

  /**
   * @generated from field: string attachment_page_label = 9;
   */
  attachmentPageLabel: string;
};

/**
 * @generated from message ablibrary.types.Page
 */
export type PageJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string book_id = 2;
   */
  bookId?: string;

  /**
   * @generated from field: int32 number = 3;
   */
  number?: number;

  /**
   * @generated from field: string label = 4;
   */
  label?: string;

  /**
   * @generated from field: int32 source_number = 5;
   */
  sourceNumber?: number;

  /**
   * @generated from field: string source_label = 6;
   */
  sourceLabel?: string;

  /**
   * @generated from field: repeated ablibrary.types.PageContent contents = 7;
   */
  contents?: PageContentJson[];

  /**
   * @generated from field: ablibrary.types.Metadata metadata = 8;
   */
  metadata?: MetadataJson;

  /**
   * @generated from field: string attachment_page_label = 9;
   */
  attachmentPageLabel?: string;
};

/**
 * Describes the message ablibrary.types.Page.
 * Use `create(PageSchema)` to create a new message.
 */
export const PageSchema: GenMessage<Page, {jsonType: PageJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_types_page, 0);

